### ISSUE TITLE
maze walls have no collision

### ISSUE THREAD

**Issue by truenicfel** [mountainflo/escape_the_maze#1]
see title

**Comment by mountainflo** [comment]
To add a collision box:
* open the static mesh object
* click on collision in the menu
* select your collision type

see: https://docs.unrealengine.com/en-us/Engine/Physics/Collision/HowTo/AddSimpleCollision

**Comment by mountainflo** [comment]
e779156528c09864c548674ea982c063f3a8d4d9 closes this issue
