### ISSUE TITLE
ducken, springen und sprinten fehlen

### ISSUE THREAD

**Issue by truenicfel** [mountainflo/escape_the_maze#5]
see title

**Comment by mountainflo** [comment]
* Go to "Project Settings" -> "Engine" -> "Input" -> "Bindings" -> "Action Mappings"
* Add mapping for "crouch" and "sprint"
* Open the Blueprint "FirstPersonCharacter" make some additions (see Jump example)

Mapping for "Jump" is with the space bar already implemented
